language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
script:
  - make test
  - make lint
after_success:
  - make docker_build
deploy:
  provider: heroku
  app: serene-shelf-51204
  api_key: ${HEROKU_API_KEY}
